In [1]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
odd_number_list = [1, 3, 5, 7]

In [5]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [6]:
two_dim_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [7]:
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [8]:
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.eye(3)#identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(3)

array([0.09542302, 0.68158592, 0.71988529])

In [23]:
np.random.rand(6)

array([0.40423092, 0.12041601, 0.60640589, 0.28596349, 0.15243138,
       0.75732766])

In [24]:
np.random.rand(3,4)

array([[8.08750692e-01, 4.95955176e-01, 2.92443688e-01, 7.27835073e-01],
       [7.63073032e-01, 2.98933741e-04, 3.02114736e-01, 3.11408194e-01],
       [6.89524273e-01, 1.48627565e-01, 4.93126156e-01, 5.70723489e-02]])

In [25]:
np.random.randn(6)

array([ 0.28158928, -1.53835314, -0.91002784,  0.46500497, -0.25052296,
        0.13699199])

In [27]:
np.random.randint(0,50,10)

array([ 6, 21, 41, 22, 46, 37,  6, 14, 31, 30])

In [28]:
rand_arr = np.random.randint(0,50,20)

In [29]:
rand_arr

array([17,  4, 12, 38, 41, 13, 11,  2, 10, 41, 11, 27, 25,  9, 20, 42, 47,
       10,  8, 42])

In [30]:
rand_arr.max()

47

In [31]:
rand_arr.argmax()

16

In [32]:
rand_arr.min()

2

In [33]:
rand_arr.argmin()

7

In [34]:
rand_arr.reshape(4,5)

array([[17,  4, 12, 38, 41],
       [13, 11,  2, 10, 41],
       [11, 27, 25,  9, 20],
       [42, 47, 10,  8, 42]])

In [36]:
rand_arr.reshape(5,4)

array([[17,  4, 12, 38],
       [41, 13, 11,  2],
       [10, 41, 11, 27],
       [25,  9, 20, 42],
       [47, 10,  8, 42]])

In [37]:
second_arr = np.arange(20)

In [38]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
second_arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
second_arr.max()

19

In [41]:
second_arr.min()

0

In [42]:
second_arr.argmax()

19

In [43]:
second_arr.shape

(20,)

In [44]:
reshaped_arr=second_arr.reshape(2,10)

In [45]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
reshaped_arr.shape

(2, 10)

In [47]:
reshaped_arr.dtype

dtype('int32')